# Generated by Django 2.2.6 on 2019-11-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('direccion', models.TextField(max_length=1000)),
                ('carrera', models.CharField(max_length=60)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
