# Generated by Django 2.2.6 on 2019-11-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=60)),
                ('delete', models.BooleanField(default=False)),
                ('re_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='myapi.Alumno')),
            ],
        ),
    ]
