# Generated by Django 2.2.6 on 2019-12-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20191127_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password',
        ),
    ]
