# Generated by Django 2.2.6 on 2019-12-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20191201_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='re_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='re_carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='myapi.Carrera'),
            preserve_default=False,
        ),
    ]
