# Generated by Django 2.2.6 on 2019-12-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20191202_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='re_carrera',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='myapi.Carrera'),
        ),
    ]
